name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1.16.5+ with JDK 17
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven for 1.16.5+ use JDK 17
        run: mvn --batch-mode --update-snapshots package
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'WorldEditSelectionManager1.16.5_JDK17'
          path: 'target/*.jar'
